import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers/Providers";
import { Header, Sidebar } from "@/features";

export const metadata: Metadata = {
  title: "Freelanceify | simplifies the freelance experiences",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Providers>
          <div className="h-[100dvh] md:grid grid-cols-[15rem_1fr] grid-rows-[auto_1fr]">
            <Header />
            <Sidebar />
            <div className="bg-gray-200 p-4">
              <div className="mx-auto max-w-screen-lg flex flex-col gap-12">{children}</div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
