import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers/Providers";
import { Header, Sidebar } from "@/features";

export const metadata: Metadata = {
  title: "Freelanceify | simplifies the freelance experiences",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Providers>
          <div className="md:grid grid-rows-[auto_1fr] grid-cols-[15rem_1fr]">
            <Header />
            <Sidebar />
            <div className="bg-secondary-100 h-[calc(100dvh-68px)] p-8 overflow-y-auto">
              <div className="mx-auto max-w-screen-lg flex flex-col gap-y-12">{children}</div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
